# NATS Configuration
nats.servers=nats://localhost:4222

# Topic Configuration
nats.topic.input=MarketAggregatedPrice
nats.topic.output=ActionEvent

# Application Configuration
app.name=bet-action-engine
app.version=0.1.0
