# Application Configuration
app.name=bet-action-engine
app.version=0.1.0

# NATS Configuration
nats.servers=nats://localhost:4222

# Crypto Price Sources
cryptoPriceSourcePriority=polymarket, binance
